
CREATE TABLE llx_mynotifications(
	-- BEGIN MODULEBUILDER FIELDS
	rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
	entity INTEGER DEFAULT 1 NOT NULL,
	label VARCHAR(255),
	qty INTEGER,
	status INTEGER,
	type INTEGER,
	date_creation DATETIME NOT NULL,
	tms TIMESTAMP NOT NULL,
	import_key VARCHAR(14)
	-- END MODULEBUILDER FIELDS
) ENGINE=innodb;